name: Verify Mergeability

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - synchronize

# runs only the latest workflow for a PR or source branch
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency (beta)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-labels:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: yashhy/pr-label-check-and-comment-action@master
        with:
          required_labels: >-
            breaking, feature, build, chore, ci, docs, fix, perf, refactor,
            revert, style, test, upgrade
          GITHUB_TOKEN: "${{ secrets.RESPOSITORY_DISPATCH_TOKEN }}"

  check-code:
    needs: check-labels
    runs-on:
      - ubuntu-latest
    env:
      MY_GITHUB_REF: ${{ github.ref }}
    steps:
      - name: Check out repo
        uses: actions/checkout@master
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: call the other repo
        env:
          MY_GITHUB_TOKEN: ${{ secrets.RESPOSITORY_DISPATCH_TOKEN }}
          EVENT: "custom_event"
          ORG: "surbhirverma"
          REPO: "hello-world-composite-run-steps-action"
        run: |
          curl \
          -X POST \
          -H "Authorization: token ${MY_GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type":"custom_event", "client_payload": {"ref":"'$MY_GITHUB_REF'"} }' \
          https://api.github.com/repos/surbhirverma/repo-dispatch-example/dispatches
